analysis/urls.py
from django.urls import path

from .views import base_views, heatmap_view, main_dash_view, indicators_view, news_view

app_name = 'analysis'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('refresh/', base_views.refresh, name='refresh'),
    path('company/', base_views.company, name='company'),
    path('heatmap/', heatmap_view.get_heatmap, name='heatmap'),
    path('portable/', main_dash_view.get_portable, name='table'),
    path('tickerInfo/', main_dash_view.ticker_info, name='ticker_info'),

    path('mailing/', main_dash_view.get_mailing, name='mailing'),
    path('mailing/send', main_dash_view.send_mailing, name='mailing_send'),
    path('mailing/<str:mail_id>', main_dash_view.delete_mailing, name='mailing_delete'),

    path('box/', main_dash_view.get_box, name='box'),
    path('indicator/macd/<str:ticker>/<int:day>', indicators_view.get_macd, name='macd'),
    path('indicator/bband/<str:ticker>', indicators_view.get_BBAND, name='bband'),
    path('indicator/rsi/<str:ticker>', indicators_view.get_RSI, name='rsi'),
    path('indicator/mfi/<str:ticker>', indicators_view.get_MFI, name='mfi'),
    path('indicator/atr/<str:ticker>', indicators_view.get_ATR, name='atr'),
    path('indicator/fi/<str:ticker>', indicators_view.get_Force_Index, name='fi'),
    path('indicator/evm/<str:ticker>', indicators_view.get_EMV, name='emv'),
    path('news/<str:news_id>/', news_view.index, name='news'),




]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from analysis import views
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("dash/", include('dash.urls')),
    path("common/", include('common.urls')),
    path("portfolio/", include('portfolio.urls')),
    path("user/", include('user.urls')),
    path("analysis/", include('analysis.urls')),
    path("", views.main_dash_view.board, name="index"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ads.txt', views.main_dash_view.Ads, name="ads")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'dash'

urlpatterns = [
    path('', base_views.index, name='article'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),


]

dash/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
    
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = RichTextUploadingField(
                                        blank=True, 
                                        null=True,
                                        external_plugin_resources=[(
                                            'youtube',
                                            '/static/vendor/ckeditor_plugins/youtube/youtube/',
                                            'plugin.js',
                                        )]

                                    )
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question', default=None, blank=True)  # 추천인 추가
    hide = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성

dash/forms.py
from django import forms
from dash.models import Question, Answer
from ckeditor.widgets import CKEditorWidget


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content', 'hide']  # QuestionForm에서 사용할 Question 모델의 속성


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer  # 사용할 모델
        fields = ['content']  # AnswerForm에서 사용할 Answer 모델의 속성

analysis/views/news_view.py
from django.shortcuts import render
from django.db.models import Q

from datetime import time, datetime

import pandas as pd
import requests
from bs4 import BeautifulSoup

from ..models import FinNews
from ..modules import get_finviz_news, get_sec_news
start = time(7, 0, 0)
end = time(9, 0, 0)
now = datetime.now()


def index(request, news_id):
    content = {}
    if news_id == "fin":
        news_list = FinNews.objects.order_by('date')

        if len(news_list) < 1:
            get_finviz_news()

        fin_news_list = news_list = news_list.filter(Q(press="fin")).distinct()
        content['news_list'] = fin_news_list
        content['press'] = 'Finviz'

    elif news_id == 'sec':
        news_list = FinNews.objects.order_by('date')
        news_list = news_list.filter(Q(press="sec")).distinct()

        if len(news_list) < 1:
            get_sec_news()

        sec_news_list = news_list.filter(Q(press="sec")).distinct()
        content['news_list'] = sec_news_list
        content['press'] = 'SEC'

    return render(request, 'main/news.html', content)

dash/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..models import Answer, Question
from ..forms import AnswerForm

from django.contrib.auth.decorators import login_required
from django.contrib import messages



def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    form = AnswerForm(request.POST)
    if form.is_valid():
        answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now(), author=request.user)
        answer.save()
    return redirect('{}#answer_{}'.format(resolve_url('dash:detail', question_id=question.id), answer.id))

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('dash:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('dash:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'dash/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('dash:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('dash:detail', question_id=answer.question.id), answer.id))

dash/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator  
from django.db.models import Q

from ..models import Question


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 25)  # 페이지당 25개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {
        'question_list': page_obj, 
        'page': page, 
        'kw': kw, 
        'hideCount':0,
        'page': "Article",
        }
    return render(request, 'main/articles.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'dash/question_detail.html', context)

def resume(request):
    photo_name = []
    for i in range(1, 14):
        photo_name.append(f"img/portfolio/port({i}).png")

    content = {"photo": photo_name}
    return render(request, 'dash/resume.html', content)

dash/views/news_view.py
from django.shortcuts import render
from pyfinviz.news import News

from analysis.modules import get_sec_news, time_in_range, get_collection, get_finviz_news
from datetime import time, datetime

import pandas as pd
import requests
from bs4 import BeautifulSoup

start = time(7, 0, 0)
end = time(9, 0, 0)
now = datetime.now()

news_collection = get_collection("news")

def news_view(request, news_id):
    content = {}


    return render(request, 'main/news.html', content)

dash/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..models import Question
from ..forms import QuestionForm

from django.contrib.auth.decorators import login_required
from django.contrib import messages


def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.author = request.user
            question.save()
            return redirect('dash:notice')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'dash/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('dash:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('dash:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'dash/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('dash:detail', question_id=question.id)
    question.delete()
    return redirect('dash:notice')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('dash:detail', question_id=question.id)

templates/dash/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/dash/news.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row text-center mb-5 mt-5">
        <h3 class="col" ><a class="newsSelect" href="{% url 'dash:news' 'fin' %}">Finviz</a></h3>
        <h3 class="col" ><a class="newsSelect" href="{% url 'dash:news' 'sec' %}">SEC</a></h3>
        <!-- <h3 class="col" ><a class="newsSelect" href="{% url 'dash:news' 'yah' %}">IMF</a></h3> -->
    </div>

    <table class="table-responsive my-table">
        <thead>
            <tr>
                {% for col in news_list.columns %}
                {% if col == "URL" %}
                {% elif col == "Headline" %}
                    <th style="padding-left:5rem">{{col}}</th>
                {% else %}
                    <th>{{col}}</th>
                {% endif %}
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for index, row in news_list.iterrows %}
            <tr>
                <td>{{row.Time}}</td>
                <td style="padding-left:5rem"><a class="newsTitle" href="{{row.URL}}">{{row.Headline}}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %} {% block script %} {% endblock script %}

templates/dash/question_detail.html
{% extends 'base.html' %}
{% load dash_filter %}
{% load i18n %}
{% block content %}


<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                {{ question.content|safe }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a
                    href="javascript:void(0)"
                    data-uri="{% url 'dash:question_vote' question.id  %}"
                    class="recommend btn btn-sm btn-outline-secondary"
                >
                    추천
                    <span class="badge rounded-pill bg-success"
                        >{{question.voter.count}}</span
                    >
                </a>
                {% if request.user == question.author %}
                <a
                    href="{% url 'dash:question_modify' question.id  %}"
                    class="btn btn-sm btn-outline-secondary"
                    >수정</a
                >
                <a
                    href="javascript:void(0)"
                    class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'dash:question_delete' question.id  %}"
                    >삭제</a
                >
                {% endif %}
            </div>
        </div>
    </div>

        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                href="javascript:void(0)">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                    >이전</a
                >
            </li>
            {% endif %}
    
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %} 
                {% if page_number >= question_list.number|add:-1 and page_number <= question_list.number|add:1 %}
                    {% if page_number == question_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" data-page="{{ page_number }}"
                            href="javascript:void(0)">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_number }}"
                            href="javascript:void(0)">{{ page_number }}</a>
                        </li>
                    {% endif %} 
                {% endif %} 
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.next_page_number }}"
                href="javascript:void(0)">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                    >다음</a
                >
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">
        {{question.answer_set.count}}개의 댓글이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                {{ answer.content|mark }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a
                    href="javascript:void(0)"
                    data-uri="{% url 'dash:answer_vote' answer.id  %}"
                    class="recommend btn btn-sm btn-outline-secondary"
                >
                    추천
                    <span class="badge rounded-pill bg-success"
                        >{{answer.voter.count}}</span
                    >
                </a>
                {% if request.user == answer.author %}
                <a
                    href="{% url 'dash:answer_modify' answer.id  %}"
                    class="btn btn-sm btn-outline-secondary"
                    >수정</a
                >
                <a
                    href="#"
                    class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'dash:answer_delete' answer.id  %}"
                    >삭제</a
                >
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form
        action="{% url 'dash:answer_create' question.id %}"
        method="post"
        class="my-3"
    >
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea
                name="content"
                id="content"
                class="form-control"
                rows="10"
            ></textarea>
        </div>
        {% if user.is_authenticated %}
        <input type="submit" value="답변등록" class="btn btn-primary" />
        {% endif %}
    </form>
</div>

{% endblock %} {% block script %}
<script type="text/javascript">
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function (element) {
        element.addEventListener("click", function () {
            if (confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            }
        });
    });

    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function (element) {
        element.addEventListener("click", function () {
            if (confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            }
        });
    });
</script>
{% endblock %}

templates/dash/question_list.html
{% extends 'base.html' %} 

{% load dash_filter %}

{% block content %}

<div class="container my-3 my-container">
    <div class="row my-3">
        <div class="col-6">
            {% if user.is_authenticated %}
            <a href="{% url 'dash:question_create' %}" class="btn btn-primary">게시글 등록하기</a>
            {% endif %}

        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table my-table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
                
            {% if question_list %} 
            {% for question in question_list %}
            {% if question.hide %}
                {% if request.user == question.author %}
                <tr class="text-center">
                    <td>
                        <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                        {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                    </td>
                    <td class="text-start"> 
                        <a class="articlTitle" href="{% url 'dash:detail' question.id %}"
                            >{{ question.subject }}</a
                        >
                        {% if question.answer_set.count > 0 %}
                        <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                        {% endif %}
                    </td>
                    <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
                    <td>{{ question.create_date|date:"Y-m-d" }}</td>
                </tr>
                {% endif %}
            {% else %}
            <tr class="text-center">
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td class="text-start"> 
                    <a class="articlTitle" href="{% url 'dash:detail' question.id %}"
                        >{{ question.subject }}</a
                    >
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
                <td>{{ question.create_date|date:"Y-m-d" }}</td>
            </tr>
            {% endif %}
            {% endfor %} {% else %}
            <tr>
                <td colspan="6" class="text-center">게시글이 없습니다.</td>
            </tr>
            {% endif %}

        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center fixed-bottom mb-5">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" data-page="{{ 1 }}"
                href="javascript:void(0)"><i class="fa fa-angle-double-left" aria-hidden="true"></i>
            </i></a>
            </li>
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                href="javascript:void(0)"><i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                ><i class="fa fa-angle-double-left" aria-hidden="true"></i>
            </a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                    ><i class="fa fa-angle-left" aria-hidden="true"></i>
                    </a
                >
            </li>
        {% endif %}

        <!-- 페이지리스트 -->
        
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number == 0 %}

            {% elif page_number == 1 %}
                
                {% if page_number == question_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" data-page="{{ page_number }}"
                        href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                    <li class="page-item" aria-current="page">
                        <a class="page-link" data-page="{{ page_number|add:1 }}"
                        href="javascript:void(0)">{{ page_number|add:1 }}</a>
                    </li>
                    <li class="page-item" aria-current="page">
                        <a class="page-link" data-page="{{ page_number|add:2 }}"
                        href="javascript:void(0)">{{ page_number|add:2 }}</a>
                    </li>
                {% endif %}


            {% elif page_number > 1 and page_number < question_list.paginator.num_pages %}
                {% if page_number == question_list.number %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_number|add:-1 }}"
                        href="javascript:void(0)">{{ page_number|add:-1 }}</a>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" data-page="{{ page_number }}"
                        href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_number|add:1 }}"
                        href="javascript:void(0)">{{ page_number|add:1 }}</a>
                    </li>
                {% endif %}
            {% else %}
                {% if page_number == question_list.number %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_number|add:-1 }}"
                        href="javascript:void(0)">{{ page_number|add:-1 }}</a>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" data-page="{{ page_number }}"
                        href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                            >{{ page_number|add:1 }}</a
                        >
                    </li>
                {% endif %}    
            {% endif %}
            
        {% endfor %}
        <!-- 다음페이지 -->

        {% if question_list.has_next %}

            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.next_page_number }}"
                href="javascript:void(0)"><i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                    ><i class="fa fa-angle-right" aria-hidden="true"></i>
                    </a
                >
            </li>
        {% endif %}
        {% if question_list.paginator %}
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ question_list.paginator.num_pages }}"
                    href="javascript:void(0)"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
                        ><i class="fa fa-angle-double-right" aria-hidden="true"></i></a
                    >
                </li>
            {% endif %}
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->


</div>
<form id="searchForm" method="get" action="{% url 'dash:article' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}


{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });

    document.querySelector('#search_kw').addEventListener('keypress', function (e) {
        if (e.key === 'Enter') {
            document.getElementById('kw').value = document.getElementById('search_kw').value;
            document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
            document.getElementById('searchForm').submit();    }
    });

    $('.my-link').bind('click', false);
</script>
{% endblock %}