analysis/urls.py
from django.urls import path

from .views import base_views, heatmap_view, main_dash_view, indicators_view, news_view

app_name = 'analysis'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('refresh/', base_views.refresh, name='refresh'),
    path('company/', base_views.company, name='company'),
    path('heatmap/', heatmap_view.get_heatmap, name='heatmap'),
    path('portable/', main_dash_view.get_portable, name='table'),
    path('tickerInfo/', main_dash_view.ticker_info, name='ticker_info'),

    path('mailing/', main_dash_view.get_mailing, name='mailing'),
    path('mailing/send', main_dash_view.send_mailing, name='mailing_send'),
    path('mailing/<str:mail_id>', main_dash_view.delete_mailing, name='mailing_delete'),

    path('box/', main_dash_view.get_box, name='box'),
    path('indicator/macd/<str:ticker>/<int:day>', indicators_view.get_macd, name='macd'),
    path('indicator/bband/<str:ticker>', indicators_view.get_BBAND, name='bband'),
    path('indicator/rsi/<str:ticker>', indicators_view.get_RSI, name='rsi'),
    path('indicator/mfi/<str:ticker>', indicators_view.get_MFI, name='mfi'),
    path('indicator/atr/<str:ticker>', indicators_view.get_ATR, name='atr'),
    path('indicator/fi/<str:ticker>', indicators_view.get_Force_Index, name='fi'),
    path('indicator/evm/<str:ticker>', indicators_view.get_EMV, name='emv'),
    path('news/<str:news_id>/', news_view.index, name='news'),




]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from analysis import views
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("dash/", include('dash.urls')),
    path("common/", include('common.urls')),
    path("portfolio/", include('portfolio.urls')),
    path("user/", include('user.urls')),
    path("analysis/", include('analysis.urls')),
    path("", views.main_dash_view.board, name="index"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ads.txt', views.main_dash_view.Ads, name="ads")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'dash'

urlpatterns = [
    path('', base_views.index, name='article'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),


]

analysis/forms.py
from django import forms
from .models import MailingTicker

class MailingForm(forms.ModelForm):
    class Meta:
        model = MailingTicker
        fields = ['ticker']  

analysis/views/base_views.py
from django.shortcuts import render
import yfinance as yf
import json
from datetime import datetime, timedelta

import pandas as pd
from pandas_datareader import data as pdr

import calendar


from tradingview_ta import TA_Handler, Interval, Exchange

yf.pdr_override()

yesterday = datetime.now() - timedelta(1)
day = datetime.strftime(yesterday, '%Y-%m-%d')

today_origin = datetime.now()
today = datetime.strftime(today_origin, '%Y-%m-%d')

week_of_day = calendar.day_name[today_origin.weekday()]

# Create your views here.
def index(request):
    content = {}
    return render(request, 'analysis/analysis_base.html', content)


def refresh(request):
    content = {}
    return render(request, 'analysis/analysis_base.html', content)


def company(request):


    ticker = request.GET.get('ticker', '')  # 검색어
    context = {"ticker":ticker}
    
    if ticker.encode().isalpha():
        stock = yf.Ticker(ticker)
        price = pdr.get_data_yahoo(ticker)
        price['Date'] = price.index
        price['Date'] = price['Date'].dt.date  
        price.index = price['Date'].astype("str")
        price.drop(['Date'], axis=1, inplace=True)
        context['stock_price'] = price.T.to_json()
        context['last_stock_price'] = round(price.iloc[-1:,3:4].values[0][0], 2) 

        context['last_diff_val'] = round(price.diff().iloc[-1:,3:4].values[0][0], 2) 
        context['last_pct_val'] = round(price.pct_change().iloc[-1:,3:4].values[0][0] * 100, 2)
        recommand_df = stock.recommendations.loc['2023-01-01':, :]
        recommand_df['Date'] = recommand_df.index
        recommand_df = recommand_df[['Date', 'Firm', 'To Grade','From Grade','Action']]
        context['recommand_col'] = list(recommand_df.columns)
        context['recommand'] = recommand_df.T.to_dict()

        return render(request, 'main/company_detail.html', context)
    else:
        return render(request, 'main/company.html', context)



def today_check():
    #날짜 셋팅
    today = datetime.date.today()

analysis/views/heatmap_view.py
from django.shortcuts import render
from yahoo_fin import stock_info as si
import yfinance as yf

def get_heatmap(request):

    snp500 = si.tickers_sp500()

    tickers = []
    deltas = []
    sectors =[]
    market_caps = []

    for ticker in snp500:
        
        try:
            ## create Ticker object
            stock = yf.Ticker(ticker)
            tickers.append(ticker)

            ## download info
            info = stock.info

            ## download sector
            sectors.append(info['sector'])

            ## download daily stock prices for 2 days
            hist = stock.history('2d')

            ## calculate change in stock price (from a trading day ago)
            deltas.append((hist['Close'][1]-hist['Close'][0])/hist['Close'][0])

            ## calculate market cap
            market_caps.append(info['sharesOutstanding'] * info['previousClose'])

            ## add print statement to ensure code is running
            print(f'downloaded {ticker}')
        except Exception as e:
            print(e)

    return render(request, 'analysis/heatmap.html')

analysis/views/indicators_view.py
from django.shortcuts import render
from django.http import JsonResponse
from datetime import datetime, timedelta
from pandas_datareader import data as pdr

from analysis.get_indicators import BBANDS, rsi, mfi, atr, ForceIndex, EMV

import yfinance as yf
import pandas as pd
import json

yesterday = datetime.now() - timedelta(1)
day = datetime.strftime(yesterday, '%Y-%m-%d')


def macd(price, slow, fast, smooth):
    exp1 = price.ewm(span = fast, adjust = False).mean()
    exp2 = price.ewm(span = slow, adjust = False).mean()
    macd = pd.DataFrame(exp1 - exp2).rename(columns = {'close':'macd'})
    signal = pd.DataFrame(macd.ewm(span = smooth, adjust = False).mean()).rename(columns = {'macd':'signal'})
    hist = pd.DataFrame(macd['macd'] - signal['signal']).rename(columns = {0:'hist'})
    frames =  [macd, signal, hist]
    df = pd.concat(frames, join = 'inner', axis = 1)
    return df


def get_macd(request, ticker, day):
    stock_price = pdr.get_data_yahoo(ticker)

    results = stock_price['Adj Close'].ewm(span = day, adjust = False).mean()
    results_json = results.to_json()
    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")


def get_BBAND(request, ticker):
    stock_price = pdr.get_data_yahoo(ticker)
    results = BBANDS(stock_price, 50)
    results = results[['MiddleBand', 'UpperBand', 'LowerBand']]
    results_json = results.to_json()

    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")


def get_RSI(request, ticker):
    stock_price = pdr.get_data_yahoo(ticker)

    # Call RSI function from the talib library to calculate RSI
    stock_price['RSI'] = rsi(stock_price['Adj Close'])
    results = stock_price[['RSI']]
    results_json = results.to_json()

    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")


def get_MFI(request, ticker):
    stock_price = pdr.get_data_yahoo(ticker)
    
    stock_price['MFI'] = mfi(stock_price['High'], stock_price['Low'], stock_price['Close'], stock_price['Volume'], 14)

    results = stock_price[['MFI']]
    results_json = results.to_json()

    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")



def get_ATR(request, ticker):
    stock_price = pdr.get_data_yahoo(ticker)

    stock_price['ATR'] = atr(stock_price['High'], stock_price['Low'], stock_price['Close'], 14)

    results = stock_price[['ATR']]
    results_json = results.to_json()

    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")


def get_Force_Index(request, ticker):
    stock_price = pdr.get_data_yahoo(ticker)

    n = 1
    stock_ForceIndex = ForceIndex(stock_price, n)
    results_json = stock_ForceIndex[['ForceIndex']].to_json()

    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")


def get_EMV(request, ticker):
    stock_price = pdr.get_data_yahoo(ticker)

    # Compute the 14-day Ease of Movement for AAPL
    n = 14
    stock_EMV = EMV(stock_price, n)
    results = stock_EMV['EMV']
    results_json = results.to_json()

    content = {
        "result":results_json,
    }

    return JsonResponse(content, content_type="application/json")

analysis/views/main_dash_view.py
from datetime import datetime, timedelta, time
from django.http import HttpResponse
from django.utils import timezone
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from analysis.modules import get_calender, get_finviz_news, get_sec_news, get_currency, get_price, get_index, get_company_infos, update_company_infos, time_in_range
from portfolio.models import Portfolio

import yfinance as yf
import pandas as pd
import json
import re
from pandas_datareader import data as pdr

from ..models import FinEventDate, FinancialEvent, FinNews, Currency, StockCompany, CompanyPrice, MailingTicker, SendMail
from ..forms import MailingForm

from django.http import JsonResponse


yf.pdr_override()

TODAY_DOWN = False

yf.pdr_override()


yesterday_origin = datetime.now() - timedelta(1)
yesterday = datetime.strftime(yesterday_origin, '%Y-%m-%d')

today_origin = datetime.now()
today = datetime.strftime(today_origin, '%Y-%m-%d')
start = time(7, 0, 0)
end = time(9, 0, 0)
now = datetime.now()

def board(request):
    nasdaq = "^IXIC"
    snp = "^GSPC"
    dow = "^DJI"
    context = {}

    # Nasdaq  
    stock = StockCompany.objects.filter(Q(ticker=nasdaq))
    if len(stock) == 0:
        get_index(nasdaq)
    stock = StockCompany.objects.filter(Q(ticker=nasdaq))
        
    price_list = CompanyPrice.objects.filter(Q(ticker=stock[0]))
    df = pd.DataFrame(list(price_list.values()))
    df = df[['adj_close_price']]

    context['nas_diff'] = round(df.diff().iloc[-1:,:].values[0][0], 2) 
    context['nas_pct'] = round(df.pct_change().iloc[-1:,:].values[0][0] * 100, 2)
    context['nasdaq'] = round(price_list[len(price_list)-1].close_price, 2) 

    # Snp
    stock = StockCompany.objects.filter(Q(ticker=snp))

    if len(stock) == 0:
        get_index(snp)
    stock = StockCompany.objects.filter(Q(ticker=snp))

    price_list = CompanyPrice.objects.filter(Q(ticker=stock[0]))
    df = pd.DataFrame(list(price_list.values()))
    df = df[['adj_close_price']]

    context['snp_diff'] = round(df.diff().iloc[-1:,:].values[0][0], 2) 
    context['snp_pct'] = round(df.pct_change().iloc[-1:,:].values[0][0] * 100, 2)
    context['snp'] = round(price_list[len(price_list)-1].close_price, 2) 

    # Dow
    stock = StockCompany.objects.filter(Q(ticker=dow))

    if len(stock) == 0:
        get_index(dow)
    stock = StockCompany.objects.filter(Q(ticker=dow))

    price_list = CompanyPrice.objects.filter(Q(ticker=stock[0]))
    df = pd.DataFrame(list(price_list.values()))
    df = df[['adj_close_price']]

    context['dow_diff'] = round(df.diff().iloc[-1:,:].values[0][0], 2) 
    context['dow_pct'] = round(df.pct_change().iloc[-1:,:].values[0][0] * 100, 2)
    context['dow'] = round(price_list[len(price_list)-1].close_price, 2) 


    # Events
    event_list = FinancialEvent.objects.order_by('event_mother')
    print(len(event_list))
    if len(event_list) == 0:
        get_calender()
        event_detail = FinancialEvent.objects.order_by('event_mother')
        context['event_detail_list'] = event_detail[:11]
    else:
        event_detail = FinancialEvent.objects.order_by('event_mother')
        context['event_detail_list'] = event_detail[:11]

    # News
    news_list = FinNews.objects.order_by('date')
    if len(event_list) == 0:
        get_finviz_news()
        sec_news_list = news_list.filter(Q(press="fin")).distinct()
        context['news_list'] = sec_news_list[:21]
    else:
        sec_news_list = news_list.filter(Q(press="fin")).distinct()
        context['news_list'] = sec_news_list[:21]

    # Currency
    currency_list = Currency.objects.order_by('date')
    if len(currency_list) == 0:
        get_currency()
        currency_list = currency_list.filter(Q(country="USD")).distinct()
        context['currency'] = currency_list[len(currency_list)-1]
    else:
        currency_list = currency_list.filter(Q(country="USD")).distinct()
        context['currency'] = currency_list[len(currency_list)-1]


    return render(request, 'main/core2.html', context)


def get_portable(request):
    portfolio = Portfolio.objects.filter(author=request.user)
    context = {"page":"Portfolio"}
    context["portfolio"] = portfolio
    return render(request, 'main/port_list.html', context)

def get_mailing(request):
    constext = {}
    try:
        send_mail = SendMail.objects.get(user=request.user)
    except:
        send_mail = SendMail(
            user=request.user,
            send_mail=True
        )
        send_mail.save()

    if request.method == 'POST':
        ticker = request.POST.get('ticker', '')  # 검색어

        try:
            try:
                MailingTicker.objects.get(ticker=ticker)
                return redirect('analysis:mailing')
            except:
                try:
                    company = StockCompany.objects.get(ticker=ticker)
                    update_company_infos(ticker, company)
                except:
                    get_company_infos(ticker)
                    company = StockCompany.objects.get(ticker=ticker)

                form = MailingForm(request.POST)

                if form.is_valid():
                    print("POST")
                    mail_ticker = form.save(commit=False)
                    mail_ticker.ticker = ticker
                    mail_ticker.company = company
                    mail_ticker.create_date = timezone.now()
                    mail_ticker.author = request.user
                    mail_ticker.save()

                    mailing = MailingTicker.objects.filter(author=request.user)
                    constext['mailing'] = mailing


                    constext['send_mail'] = send_mail
                    return redirect('analysis:mailing')
                else:
                    print("not valid")
        except:
            return redirect('analysis:mailing')



    mailing = MailingTicker.objects.filter(author=request.user)
    if time_in_range(start, end, now.time()):
        for mail in mailing:
            ticker = mail.ticker
            company = mail.company
            update_company_infos(ticker, company)
            
    mailing = MailingTicker.objects.filter(author=request.user)

    constext['mailing'] = mailing
    constext['send_mail'] = send_mail

    if len(mailing) > 0:
        constext['current_ticker'] = mailing[0]


    return render(request, 'main/mailing.html', constext)

def get_box(request):
    return render(request, 'main/box.html')


def delete_mailing(request, mail_id):
    print(mail_id)
    mail_ticker = MailingTicker.objects.get(id=mail_id)
    mail_ticker.delete()
    return redirect('analysis:mailing')

def send_mailing(request):
    user = request.user
    try:
        send_mail = SendMail.objects.get(user=user)
    except:
        send_mail = SendMail(
            user=user,
            send_mail=True
        )
        send_mail.save()
    content = {}
    if send_mail.send_mail:
        send_mail.send_mail = False
        send_mail.save()
        send = False
    else:
        send_mail.send_mail = True
        send_mail.save()
        send = True
    content['sendMail'] = send
    return JsonResponse(content, content_type="application/json")



def ticker_info(request):
    return


def Ads(request):
    return HttpResponse("google.com, pub-2835834888306304, DIRECT, f08c47fec0942fa0")

templates/analysis/analysis_base.html
{% extends 'base.html' %}
{% load static %}
{% load dash_filter %}

{% block style %}
    <!-- dash CSS -->
    <link
        rel="stylesheet"
        type="text/css"
        href="{% static 'style.css' %}"
    />
{% endblock style %}
{% block content %}


<div class="contianer">
    {% if currency %}
    <div class="container text-center justify mb-5">

        <h3>Currency (KRW)  {{today}} 
            <a
            href="{% url 'analysis:refresh' %}"
            class="delete btn btn-sm btn-outline-secondary"
            ><i class="fa fa-refresh" aria-hidden="true"></i></a>   
        </h3>
        <table class="table" id="table_id">
            <thead>
                <tr class="text-center table-dark">
                    <th>Code</th>
                    <th>Nation</th>
                    <th>Current</th>
                    <th>Day before</th>
                    <th>Day Change</th>
                    <th>Buy</th>
                    <th>Sell</th>
                    <th>Send</th>
                    <th>Receive</th>
                </tr>
            </thead>

            <tbody>
                {% for keys, val in currency.items %}
                    {% for code, dicts in val.items %}
                    <tr class="text-center">
                        <td>
                            {{ code }}
                        </td>
                        {% for key, value in dicts.items %}
                            <td class="text-start text-center " colspan="1"> 
                                {{ value }}
                            </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}

                {% endfor %} 
            </tbody>
        </table>
    </div>
    {% endif %}

</div>

{% endblock content %}


{% block script %}

<script>

</script>

{% endblock script %}

templates/analysis/company.html
{% extends 'base.html' %} 
{% load static %}
{% load dash_filter %}
{% block content %}

<div class="container">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <div>
        <h3 class="text-center mt-5">Search Company</h3>
        <div class="container my-3 d-flex justify-content-center">
            <div class="col-8">
                <div class="input-group col-xs-4">
                    <input
                        placeholder="Search by Ticker (e.g. AAPL)"
                        type="text"
                        id="search_ticker"
                        class="form-control"
                        value="{{ ticker|default_if_none:'' }}"
                    />
                    <div class="input-group-append">
                        <button
                            class="btn btn-outline-secondary"
                            type="button"
                            id="btn_search"
                        >
                            Search
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<form id="searchForm" method="get" action="{% url 'analysis:company' %}">
    <input
        type="hidden"
        id="ticker"
        name="ticker"
        value="{{ ticker|default_if_none:'' }}"
    />
</form>

<div class="cotainer">

    <div class="container mb-5">
        <div id="chartContainer" style="height: 600px; width: 100%"></div>
    </div>


    {% if infos %} 
    <div class="container">
        <h3>Current Price: ${{infos.currentPrice}}</h3>
        <h3>Exchange Price : ₩{{ current_krw }}</h3>
        <h3>Target Median Price: ${{infos.targetMedianPrice}}</h3>
    </div>
    {% else %} 

    {% endif %}

    <br />
    {% if dict_fs %}
    <div class="container">
        <h3>Financial Statement</h3>
        {% for key, value in dict_fs.items %}
            {% if forloop.counter == 1 %}
            <div class="row">
                <div class="btn-group mx-auto mb-2 col" role="group" aria-label="Basic example">
                    {% for keys, val in value.items %}
                        {% if val != 'None' and forloop.counter < len_fs %}
                            <button type="button" class="accountSubject btn btn-primary" >{{keys}}</button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="btn-group mx-auto col mb-5" role="group" aria-label="Basic example">
                    {% for keys, val in value.items %}
                        {% if val != 'None' %}
                            {% if forloop.counter > len_fs %}
                                <button type="button" class="accountSubject btn btn-primary" >{{keys}}</button>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% endfor %}

        <h3>Balance Sheet</h3>
        {% for key, value in dict_bs.items %}
            {% if forloop.counter == 1 %}
            <div class="row">
                <div class="btn-group mx-auto mb-2 col" role="group" aria-label="Basic example">
                    {% for keys, val in value.items %}
                        {% if val != 'None' and forloop.counter < len_bs %}
                            <button type="button" class="accountSubject btn btn-primary" >{{keys}}</button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="btn-group mx-auto col mb-5" role="group" aria-label="Basic example">
                    {% for keys, val in value.items %}
                        {% if val != 'None' %}
                            {% if forloop.counter > len_fs %}
                                <button type="button" class="accountSubject btn btn-primary" >{{keys}}</button>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% endfor %}

        
        <h3>Cashflow</h3>
        {% for key, value in dict_cf.items %}
            {% if forloop.counter == 1 %}
            <div class="row">
                <div class="btn-group mx-auto mb-2 col" role="group" aria-label="Basic example">
                    {% for keys, val in value.items %}
                        {% if val != 'None' and forloop.counter < len_cf %}
                            <button type="button" class="accountSubject btn btn-primary" >{{keys}}</button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="btn-group mx-auto col mb-5" role="group" aria-label="Basic example">
                    {% for keys, val in value.items %}
                        {% if val != 'None' %}
                            {% if forloop.counter > len_cf %}
                                <button type="button" class="accountSubject btn btn-primary" >{{keys}}</button>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <br>
    <div class="contianer">
        {% if infos %}
        <div class="container text-center justify mb-5">
            <table class="table" id="table_id">
                <thead>
                    <tr class="text-center table-dark">
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                </thead>

                <tbody>
                    {% for keys, val in infos.items %}
                    <tr class="text-center">
                        <td>
                            {{ keys }}
                        </td>
                        <td class="text-start text-center " colspan="1"> 
                            {{ val }}
                        </td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
        </div>
        {% endif %}

    </div>



</div>


<input
    type="hidden"
    id="stock_price"
    name="variable"
    value="{{ stock_price }}"
/>
<input type="hidden" id="stock_ticker" name="variable" value="{{ ticker }}" />
<input type="hidden" id="stock_fs" name="variable" value="{{ financial }}" />
<input type="hidden" id="stock_bs" name="variable" value="{{ balance }}" />
<input type="hidden" id="stock_cf" name="variable" value="{{ cashflow }}" />



{% endblock content %} {% block script %}
<script type="text/javascript" src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.stock.min.js"></script>
<script src={% static 'js/stock_chart.js' %}></script>

{% endblock script %} 

templates/analysis/heatmap.html
{% extends 'base.html' %} 

{% block content %}
{% endblock content %}

{% block script %}
{% endblock script %}