analysis/urls.py
from django.urls import path

from .views import base_views, heatmap_view, main_dash_view, indicators_view, news_view

app_name = 'analysis'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('refresh/', base_views.refresh, name='refresh'),
    path('company/', base_views.company, name='company'),
    path('heatmap/', heatmap_view.get_heatmap, name='heatmap'),
    path('portable/', main_dash_view.get_portable, name='table'),
    path('tickerInfo/', main_dash_view.ticker_info, name='ticker_info'),

    path('mailing/', main_dash_view.get_mailing, name='mailing'),
    path('mailing/send', main_dash_view.send_mailing, name='mailing_send'),
    path('mailing/<str:mail_id>', main_dash_view.delete_mailing, name='mailing_delete'),

    path('box/', main_dash_view.get_box, name='box'),
    path('indicator/macd/<str:ticker>/<int:day>', indicators_view.get_macd, name='macd'),
    path('indicator/bband/<str:ticker>', indicators_view.get_BBAND, name='bband'),
    path('indicator/rsi/<str:ticker>', indicators_view.get_RSI, name='rsi'),
    path('indicator/mfi/<str:ticker>', indicators_view.get_MFI, name='mfi'),
    path('indicator/atr/<str:ticker>', indicators_view.get_ATR, name='atr'),
    path('indicator/fi/<str:ticker>', indicators_view.get_Force_Index, name='fi'),
    path('indicator/evm/<str:ticker>', indicators_view.get_EMV, name='emv'),
    path('news/<str:news_id>/', news_view.index, name='news'),




]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='main/sign-in.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from analysis import views
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("dash/", include('dash.urls')),
    path("common/", include('common.urls')),
    path("portfolio/", include('portfolio.urls')),
    path("user/", include('user.urls')),
    path("analysis/", include('analysis.urls')),
    path("", views.main_dash_view.board, name="index"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ads.txt', views.main_dash_view.Ads, name="ads")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'dash'

urlpatterns = [
    path('', base_views.index, name='article'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),


]

portfolio/urls.py
from django.urls import path

from .views import base_views, port_view

app_name = 'portfolio'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('<int:port_id>/', base_views.detail, name='detail'),
    path('portfolio/delete/<int:port_id>/', base_views.port_delete, name="port_delete"),
    path('stock/create/<int:port_id>/', port_view.stock_create, name="stock_create"),
    path('stock/delete/<int:port_id>/<int:stock_id>/', port_view.stock_delete, name="stock_delete")

    
]

analysis/views/base_views.py
from django.shortcuts import render
import yfinance as yf
import json
from datetime import datetime, timedelta

import pandas as pd
from pandas_datareader import data as pdr

import calendar


from tradingview_ta import TA_Handler, Interval, Exchange

yf.pdr_override()

yesterday = datetime.now() - timedelta(1)
day = datetime.strftime(yesterday, '%Y-%m-%d')

today_origin = datetime.now()
today = datetime.strftime(today_origin, '%Y-%m-%d')

week_of_day = calendar.day_name[today_origin.weekday()]

# Create your views here.
def index(request):
    content = {}
    return render(request, 'analysis/analysis_base.html', content)


def refresh(request):
    content = {}
    return render(request, 'analysis/analysis_base.html', content)


def company(request):


    ticker = request.GET.get('ticker', '')  # 검색어
    context = {"ticker":ticker}
    
    if ticker.encode().isalpha():
        stock = yf.Ticker(ticker)
        price = pdr.get_data_yahoo(ticker)
        price['Date'] = price.index
        price['Date'] = price['Date'].dt.date  
        price.index = price['Date'].astype("str")
        price.drop(['Date'], axis=1, inplace=True)
        context['stock_price'] = price.T.to_json()
        context['last_stock_price'] = round(price.iloc[-1:,3:4].values[0][0], 2) 

        context['last_diff_val'] = round(price.diff().iloc[-1:,3:4].values[0][0], 2) 
        context['last_pct_val'] = round(price.pct_change().iloc[-1:,3:4].values[0][0] * 100, 2)
        recommand_df = stock.recommendations.loc['2023-01-01':, :]
        recommand_df['Date'] = recommand_df.index
        recommand_df = recommand_df[['Date', 'Firm', 'To Grade','From Grade','Action']]
        context['recommand_col'] = list(recommand_df.columns)
        context['recommand'] = recommand_df.T.to_dict()

        return render(request, 'main/company_detail.html', context)
    else:
        return render(request, 'main/company.html', context)



def today_check():
    #날짜 셋팅
    today = datetime.date.today()

dash/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator  
from django.db.models import Q

from ..models import Question


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 25)  # 페이지당 25개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {
        'question_list': page_obj, 
        'page': page, 
        'kw': kw, 
        'hideCount':0,
        'page': "Article",
        }
    return render(request, 'main/articles.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'dash/question_detail.html', context)

def resume(request):
    photo_name = []
    for i in range(1, 14):
        photo_name.append(f"img/portfolio/port({i}).png")

    content = {"photo": photo_name}
    return render(request, 'dash/resume.html', content)

portfolio/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator  
from django.db.models import Q

from pandas_datareader import data as pdr
import yfinance as yf
import pandas as pd

from ..models import Portfolio, Stock
from ..forms import PortfolioForm, StockForm

from tradingview_ta import TA_Handler, Interval, Exchange


import calendar

from datetime import datetime, timedelta, date
import calendar
import json

today = datetime.now()
today = datetime.strftime(today, '%Y-%m-%d')
monthly_return = {

}


def index(request):
    if request.method == 'POST':
        form = PortfolioForm(request.POST)
        if form.is_valid():
            port = form.save(commit=False)
            port.target_price = 0
            port.create_date = timezone.now()
            port.author = request.user
            port.save()
            return redirect('portfolio:index')

    symbol = request.GET.get("ticker", "")
    context = {"page":"Portfolio"}
    context['ticker'] = symbol
    portfolio = Portfolio.objects.order_by('-create_date')
    if symbol:
        data = yf.Ticker(symbol)
        data_info = data.cashflow
        context['result'] = data_info.to_html
    context["portfolio"] = portfolio
    print()


    return render(request, 'main/port_list.html', context)



def detail(request, port_id):

    today_month = date.today()
    last_month = today_month - timedelta(days=1)
    today_year = today_month.year

    today_month = today_month.strftime("%Y-%m").split("-")[1]
    last_month = last_month.strftime("%Y-%m").split("-")[1]

    port = get_object_or_404(Portfolio, pk=port_id)
    total_value = 0
    if len(port.stock_port.all()) > 0:
        port_value = {}
        for stock in port.stock_port.all():
            buy_year = stock.buy_dates.split("-")[0]
            ticker = stock.ticker
            stock_price = pdr.get_data_yahoo(ticker)
            new_df = stock_price.loc[stock.buy_dates:,]
            end_of_month = []

            stock_ta = TA_Handler(
                symbol=ticker,
                screener="america",
                exchange="NASDAQ",
                interval=Interval.INTERVAL_1_DAY,
            )

            recommandation = stock_ta.get_analysis().summary

            stock.recommandation = recommandation['RECOMMENDATION']
            
            for year in range(int(buy_year), int(today_year)+1):
                for i in range(1, 13):
                    input_dt = datetime(year, i, 13)
                    res = calendar.monthrange(input_dt.year, input_dt.month)
                    day = res[1]
                    end_of_month.append(f"{input_dt.year}-{input_dt.month}-{input_dt.day}")
            print(end_of_month)

            end_of_month_price = {}
            for day in end_of_month:
                try:
                    end_of_month_price[day] = new_df.loc[day,"Adj Close"][-1]
                except:
                    pass
            
            price_df = pd.DataFrame(end_of_month_price, index=['Close']).T

            price_df['buy_price'] = stock.buy_price
            price_df['profit'] = (price_df['Close'] - price_df['buy_price']) * stock.quantity
            profit_dict = price_df[['profit']].T.to_dict()

            json_val = json.dumps(profit_dict)
            stock.profit_history = json_val
            print(end_of_month)
            print(json_val)


            last_quote = new_df['Adj Close'].iloc[-1]
            stock.current_price = round(last_quote, 2)
            stock.profit = round((stock.current_price - stock.buy_price) * stock.quantity, 2)
            stock.evaluated = round(stock.quantity * stock.current_price, 2)
            stock.return_ratio = round((1 - (stock.buy_price / stock.current_price)) * 100, 2)
            stock.save()

            price_df = new_df[['Adj Close']]
            price_df['Current Value'] = price_df['Adj Close'] * stock.quantity
            price_df['Date'] = price_df.index
            price_df.index = price_df['Date'].apply(lambda x: x.date().strftime('%Y-%m-%d'))

            port_value[stock.ticker] = stock.evaluated
            total_value += stock.evaluated

        if port.port_history == "":
            history = {
                stock.ticker : price_df[['Current Value']].T.to_dict()
            }
            
            json_val = json.dumps(history)
            port.port_history = json_val
        else:
            port_dict = json.loads(port.port_history)
            port_dict[stock.ticker] = price_df[['Current Value']].T.to_dict()

            json_val = json.dumps(port_dict)
            port.port_history = json_val

        port.port_value = total_value
        total_value = round(total_value, 2)
    else:
        port.port_value = 0
    port.save()
    context = {'portfolio':port, "total_value" : total_value, "page":"Portfolio"}
    return render(request, 'main/port_detail.html', context)


def port_delete(request, port_id):
    print(port_id)
    port = Portfolio.objects.get(id=port_id)
    port.delete()
    return redirect('portfolio:index')

user/views/base_views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'main/profile.html')

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="ko">
    <head>


        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <!-- Bootstrap CSS -->
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'bootstrap.min.css' %}"
        />


        <link
            href="{% static 'fontawesomefree/css/fontawesome.css' %}"
            rel="stylesheet"
            type="text/css"
        />
        <link
            href="{% static 'fontawesomefree/css/brands.css' %}"
            rel="stylesheet"
            type="text/css"
        />
        <link
            href="{% static 'fontawesomefree/css/solid.css' %}"
            rel="stylesheet"
            type="text/css"
        />

        <link
            rel="stylesheet"
            type="text/css"
            href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css"
        />
        <link rel="stylesheet" href="{% static 'bootstrap-datepicker.css' %}" />
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css"
            rel="stylesheet"
            type="text/css"
        />
        <!-- Google fonts-->
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
            rel="stylesheet"
            type="text/css"
        />
        <link
            href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700"
            rel="stylesheet"
            type="text/css"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&family=Open+Sans:wght@300&display=swap"
            rel="stylesheet"
        />


        <link rel="stylesheet"
            href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">

        <!-- dash CSS -->
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'style.css' %}"
        />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2835834888306304"
        crossorigin="anonymous"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>

        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
        
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script
            type="text/javascript"
            charset="utf8"
            src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"
        ></script>
        <script src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

        <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.ko.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src={% static 'js/scripts.js' %}></script>
        <script>hljs.highlightAll();</script>


        
        <title>JUNSS</title>
    </head>
    <body>
        {% include 'navbar.html' %} 
        {% block content %} 
        {% endblock content %}
        <!-- 자바스크립트 Start -->
        {% block script %} {% endblock %}
        <!-- 자바스크립트 End -->
    </body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom nav-fill w-100">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">JUNSS</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dash:article' %}">Article</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dash:news' 'fin' %}">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'analysis:company'%}">Company Infos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'analysis:index'%}">Currency Exchange Rate</a>
                </li>
                <li class="nav-item">
                    <!-- <a class="nav-link" href="{% url 'analysis:index' %}">Fundamental Analysis using Ratios</a> -->
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'portfolio:index' %}">포트폴리오</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}"
                        >{{ user.username }} (로그아웃)</a
                    >
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}"
                        >로그인</a
                    >
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}"
                        >회원가입</a
                    >
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</nav>


<script>
    $(".mode-switch").on("click", () => {
        $("body").toggleClass("dark");
        $("button").toggleClass("on");
        $("#btn-toggle").toggleClass("on");
        $("#sun").toggleClass("off");
      });
</script>