analysis/urls.py
from django.urls import path

from .views import base_views, heatmap_view, main_dash_view, indicators_view, news_view

app_name = 'analysis'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('refresh/', base_views.refresh, name='refresh'),
    path('company/', base_views.company, name='company'),
    path('heatmap/', heatmap_view.get_heatmap, name='heatmap'),
    path('portable/', main_dash_view.get_portable, name='table'),
    path('tickerInfo/', main_dash_view.ticker_info, name='ticker_info'),

    path('mailing/', main_dash_view.get_mailing, name='mailing'),
    path('mailing/send', main_dash_view.send_mailing, name='mailing_send'),
    path('mailing/<str:mail_id>', main_dash_view.delete_mailing, name='mailing_delete'),

    path('box/', main_dash_view.get_box, name='box'),
    path('indicator/macd/<str:ticker>/<int:day>', indicators_view.get_macd, name='macd'),
    path('indicator/bband/<str:ticker>', indicators_view.get_BBAND, name='bband'),
    path('indicator/rsi/<str:ticker>', indicators_view.get_RSI, name='rsi'),
    path('indicator/mfi/<str:ticker>', indicators_view.get_MFI, name='mfi'),
    path('indicator/atr/<str:ticker>', indicators_view.get_ATR, name='atr'),
    path('indicator/fi/<str:ticker>', indicators_view.get_Force_Index, name='fi'),
    path('indicator/evm/<str:ticker>', indicators_view.get_EMV, name='emv'),
    path('news/<str:news_id>/', news_view.index, name='news'),




]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from analysis import views
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("dash/", include('dash.urls')),
    path("common/", include('common.urls')),
    path("portfolio/", include('portfolio.urls')),
    path("user/", include('user.urls')),
    path("analysis/", include('analysis.urls')),
    path("", views.main_dash_view.board, name="index"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ads.txt', views.main_dash_view.Ads, name="ads")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'dash'

urlpatterns = [
    path('', base_views.index, name='article'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),


]

portfolio/urls.py
from django.urls import path

from .views import base_views, port_view

app_name = 'portfolio'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('<int:port_id>/', base_views.detail, name='detail'),
    path('portfolio/delete/<int:port_id>/', base_views.port_delete, name="port_delete"),
    path('stock/create/<int:port_id>/', port_view.stock_create, name="stock_create"),
    path('stock/delete/<int:port_id>/<int:stock_id>/', port_view.stock_delete, name="stock_delete")

    
]

dash/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
    
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = RichTextUploadingField(
                                        blank=True, 
                                        null=True,
                                        external_plugin_resources=[(
                                            'youtube',
                                            '/static/vendor/ckeditor_plugins/youtube/youtube/',
                                            'plugin.js',
                                        )]

                                    )
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question', default=None, blank=True)  # 추천인 추가
    hide = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성

portfolio/views/port_view.py
from django.shortcuts import render, get_object_or_404, redirect
import json

from ..forms import StockForm
from ..models import Stock, Portfolio

def stock_create(request, port_id):
    port = get_object_or_404(Portfolio, pk=port_id)
    form = StockForm(request.POST)
    if form.is_valid():
        ticker = request.POST.get('ticker')
        buy_price = float(request.POST.get('buy_price'))
        quantity = int(request.POST.get('quantity'))
        buy_date = request.POST.get('datepicker')

        stock_list = Stock.objects.filter(portfolio=port_id, ticker=ticker)
        if len(stock_list) != 0:
            stocks = stock_list
            total_price = stocks.buy_price * stocks.quantity
            new_price = buy_price * quantity
            total_quantity = stocks.quantity + quantity
            stocks.buy_price = (total_price + new_price) / total_quantity
            stocks.quantity += quantity
            stocks.save()
        else:
            stocks = Stock(portfolio=port, ticker=ticker, quantity=quantity, buy_price=buy_price, buy_dates=buy_date)
            stocks.save()
        return redirect('portfolio:detail', port_id)
    else:
        print("fail")
        return redirect('portfolio:detail', port_id)


def stock_delete(request, port_id, stock_id):
    port = get_object_or_404(Portfolio, pk=port_id)
    stock = Stock.objects.get(id=stock_id)
    history = json.loads(port.port_history)
    print(history)
    for key, value in history.items():
        if stock.ticker in value.keys():
            value.pop(stock.ticker, None)
    port.save()
    stock.delete()
    return redirect('portfolio:detail', port_id)

templates/port/portfolio_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row mt-3">
        <h1>Portfolio - <b>{{portfolio.title}}</b></h1>

        <div class="container text-center justify mb-5">
            <div class="row">
                <h1>Add Stock</h1>
                <form class="input-group mb-3 row" id="stockForm" method="post" action="{% url 'portfolio:stock_create' portfolio.id %}">
                    {% csrf_token %}
                    <input type="text" class="form-control col-3" placeholder="Ticker (e.g. AAPL)" aria-label="Ticker" aria-describedby="basic-addon1" id="ticker" name="ticker">
                    <input type="number" min="0" step="0.0001" class="form-control col-3" placeholder="Buy Price (USD)" aria-label="Price" aria-describedby="basic-addon1" id="buy_price" name="buy_price">
                    <input type="number" min="0" step="1" class="form-control col-3" placeholder="Quantity" aria-label="Quantity" aria-describedby="basic-addon1" id="quantity" name="quantity">
                    <input type="text" id="datePicker" class="form-control" value="" placeholder="Pick buy date">
                    <input type="submit" class="btn btn-info btn-floating col-1" value="Add">

                </form>
            </div>
        </div>

        
        <table class="table" id="table_id">
            <thead>
                <tr class="text-center table-dark">
                    <th>번호</th>
                    <th>종목코드</th>
                    <th>보유수량</th>
                    <th>평균단가</th>
                    <th>현재가</th>
                    <th>평균목표가</th>
                    <th>수익률</th>
                    <th>평가금액</th>
                    <th>평가손익</th>
                    <th>삭제</th>
                </tr>
            </thead>

            <tbody>
                {% if portfolio.stock_port %} 
                {% for stock in portfolio.stock_port.all %}
                <tr class="text-center">
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td class="text-start text-center "> 
                        <a href="{% url 'analysis:company' %}">{{ stock.ticker.upper }}</a>
                    </td>
                    <td class="text-start text-center " colspan="1"> 
                        {{ stock.quantity }}
                    </td>
                    <td class="text-start text-center "> 
                        <i class="fa fa-usd" aria-hidden="true"></i>
                        {{ stock.buy_price }}
                    </td>
                    <td class="text-start text-center "> 
                        <i class="fa fa-usd" aria-hidden="true"></i>
                        {{ stock.current_price }}
                    </td>
                    <td class="text-start text-center "> 
                        <i class="fa fa-usd" aria-hidden="true"></i>
                        {{ stock.target_price }}
                    </td>
                    <td class="text-start text-center "> 
                        {% if stock.return_ratio > 0 %}
                            <div style="color:red;"><b> + {{ stock.return_ratio }} %</b></div>
                        {% else %}
                            <div style="color:blue;"><b>{{ stock.return_ratio }} %</b></div>
                        {% endif %}
                    </td>
                    <td class="text-start text-center "> 
                        <i class="fa fa-usd" aria-hidden="true"></i>
                        {{ stock.evaluated }}
                    </td>

                    <td class="text-start text-center "> 
                        {% if stock.return_ratio > 0 %}
                            <div style="color:red;">
                                <i class="fa fa-usd" aria-hidden="true"></i>
                                <b>  +{{ stock.profit }} </b></div>
                        {% else %}
                            <div style="color:blue;"> 
                                <i class="fa fa-usd" aria-hidden="true"></i>
                                <b>{{ stock.profit }}</b>
                            </div>
                        {% endif %}
                        
                    </td>

                    <td class="text-start text-center "> 
                        <a
                            href="javascript:void(0)"
                            class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'portfolio:stock_delete' port_id=portfolio.id stock_id=stock.id  %}"
                            ><i class="fa fa-trash" aria-hidden="true"></i></a
                        >
                    </td>
                </tr>
                {% endfor %} 
                {% else %}
                <tr>
                    <td colspan="9" class="text-center">종목이 없습니다.</td>
                </tr>
                {% endif %}

            </tbody>
        </table>
        <div>
            {% if portfolio.stock_port %} 
            Total Value : <i class="fa fa-usd" aria-hidden="true"></i> {{ total_value }}
            {% endif %}
        </div>
    </div>
</div>


{% endblock content %}


{% block script %}
<script>

    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function (element) {
        element.addEventListener("click", function () {
            if (confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            }
        });
    });
    

    $(document).ready( function () {
        $('#table_id').DataTable();
    } );


    $(function() {	
		$('#datePicker').datepicker({
		    format: "yyyy-mm-dd",	//데이터 포맷 형식(yyyy : 년 mm : 월 dd : 일 )
		    startDate: '-3650d',	//달력에서 선택 할 수 있는 가장 빠른 날짜. 이전으로는 선택 불가능 ( d : 일 m : 달 y : 년 w : 주)
		    endDate: '+0d',	//달력에서 선택 할 수 있는 가장 느린 날짜. 이후로 선택 불가 ( d : 일 m : 달 y : 년 w : 주)
		    autoclose : true,	//사용자가 날짜를 클릭하면 자동 캘린더가 닫히는 옵션
		    calendarWeeks : false, //캘린더 옆에 몇 주차인지 보여주는 옵션 기본값 false 보여주려면 true
		    clearBtn : false, //날짜 선택한 값 초기화 해주는 버튼 보여주는 옵션 기본값 false 보여주려면 true
		    datesDisabled : [],//선택 불가능한 일 설정 하는 배열 위에 있는 format 과 형식이 같아야함.
		    daysOfWeekDisabled : [0,6],	//선택 불가능한 요일 설정 0 : 일요일 ~ 6 : 토요일
		    daysOfWeekHighlighted : [], //강조 되어야 하는 요일 설정
		    disableTouchKeyboard : false,	//모바일에서 플러그인 작동 여부 기본값 false 가 작동 true가 작동 안함.
		    immediateUpdates: false,	//사용자가 보는 화면으로 바로바로 날짜를 변경할지 여부 기본값 :false 
		    multidate : false, //여러 날짜 선택할 수 있게 하는 옵션 기본값 :false 
		    multidateSeparator :",", //여러 날짜를 선택했을 때 사이에 나타나는 글짜 2019-05-01,2019-06-01
		    templates : {
		        leftArrow: '&laquo;',
		        rightArrow: '&raquo;'
		    }, //다음달 이전달로 넘어가는 화살표 모양 커스텀 마이징 
		    showWeekDays : true ,// 위에 요일 보여주는 옵션 기본값 : true
		    todayHighlight : true ,	//오늘 날짜에 하이라이팅 기능 기본값 :false 
		    toggleActive : true,	//이미 선택된 날짜 선택하면 기본값 : false인경우 그대로 유지 true인 경우 날짜 삭제
		    weekStart : 0 ,//달력 시작 요일 선택하는 것 기본값은 0인 일요일 
		    language : "ko"	//달력의 언어 선택, 그에 맞는 js로 교체해줘야한다.
		    
		});//datepicker end
	});//ready end

</script>
{% endblock script %}

templates/port/portfolio_list.html
{% extends 'base.html' %} {% block content %}


<div class="container text-center justify">
    <div class="row">
        <h1 class="mb-3">Add portfolio</h1>
        <div class="input-group mb-3 col">
            <input type="text" class="form-control" placeholder="Portfolio title" aria-label="Username" aria-describedby="basic-addon1" id="portfolio_title">
            <button type="button" class="btn btn-info btn-floating col-1" id="btn_port">
                <i class="fa-solid fa-plus"></i>
            </button>
        </div>

    </div>
</div>

<div class="container my-3">
    <div class="row">
        <div class="list-group">
            <h4>Portpolio list</h4> 
            <table class="table">
                <thead>
                    <tr class="text-center table-dark">
                        <th>번호</th>
                        <th style="width:50%">제목</th>
                        <th>작성일</th>
                    </tr>
                </thead>
                <tbody>
                    {% if portfolio %} 
                    {% for port in portfolio %}
                    <tr class="text-center">
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td class="text-start text-center "> 
                            <a href="{% url 'portfolio:detail' port.id %}"
                                >{{ port.title }}</a
                            >
                            {% if port.answer_set.count > 0 %}
                            <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                            {% endif %}
                        </td>
                        <td>{{ port.create_date|date:"Y-m-d" }}</td>
                    </tr>
                    {% endfor %} {% else %}
                    <tr>
                        <td colspan="3">등록된 포트폴리오가 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<form id="portForm" method="post" action="{% url 'portfolio:index' %}">
    {% csrf_token %}
    <input type="hidden" id="port_title" name="title" value="{{ title|default_if_none:'' }}">
</form>

{% endblock content %} 

{% block script %}
<script type="text/javascript">

    const btn_port = document.getElementById("btn_port");
    btn_port.addEventListener("click", function () {
        document.getElementById("port_title").value = document.getElementById("portfolio_title").value;
        document.getElementById("portForm").submit();
    });

    document
        .querySelector("#portfolio_title")
        .addEventListener("keypress", function (e) {
            if (e.key === "Enter") {
                document.getElementById("port_title").value = document.getElementById("portfolio_title").value;
                document.getElementById("portForm").submit();
            }
        });



</script>
{% endblock %}